<?php

defined( 'ABSPATH' ) || exit;

final class SWI_Admin {
	/** @var SWI_Analytics */ private $analytics;
	public function __construct( SWI_Analytics $analytics ) { $this->analytics = $analytics; }
	public function hooks() {
		add_action( 'admin_menu', array( $this, 'add_page' ) );
		add_action( 'admin_post_swi_save_settings', array( $this, 'save_settings' ) );
		add_action( 'admin_post_swi_reset_settings', array( $this, 'reset_settings' ) );
		add_action( 'admin_post_swi_approve_visual', array( $this, 'approve_visual' ) );
		add_action( 'admin_post_swi_restore_snapshot', array( $this, 'restore_snapshot' ) );
		add_action( 'admin_enqueue_scripts', array( $this, 'enqueue_assets' ) );
		add_filter( 'plugin_action_links_' . SWI_BASENAME, array( $this, 'action_links' ) );
	}
	public function add_page() { add_options_page( __( 'Sabri Welcome Intro', 'sabri-welcome-intro' ), __( 'Sabri Welcome Intro', 'sabri-welcome-intro' ), swi_manage_capability(), 'sabri-welcome-intro', array( $this, 'render_page' ) ); }
	public function enqueue_assets( $hook ) { if ( 'settings_page_sabri-welcome-intro' !== $hook ) return; wp_enqueue_style( 'swi-admin', SWI_URL . 'assets/css/admin.css', array(), SWI_VERSION ); wp_enqueue_script( 'swi-admin', SWI_URL . 'assets/js/admin.js', array(), SWI_VERSION, true ); wp_localize_script( 'swi-admin', 'swiAdmin', array( 'confirmReset' => __( 'Restore the safe default Welcome Intro settings?', 'sabri-welcome-intro' ) ) ); }
	public function action_links( $links ) { array_unshift( $links, '<a href="' . esc_url( admin_url( 'options-general.php?page=sabri-welcome-intro' ) ) . '">' . esc_html__( 'Settings', 'sabri-welcome-intro' ) . '</a>' ); return $links; }
	private function require_manage() { if ( ! swi_current_user_can_manage() ) wp_die( esc_html__( 'You are not allowed to manage these settings.', 'sabri-welcome-intro' ), '', array( 'response' => 403 ) ); }
	private function bool_post( $key ) { return isset( $_POST[ $key ] ) ? 1 : 0; }

	public function save_settings() {
		$this->require_manage(); check_admin_referer( 'swi_save_settings' );
		$raw = array(
			'enabled' => $this->bool_post( 'enabled' ), 'frequency_days' => isset( $_POST['frequency_days'] ) ? wp_unslash( $_POST['frequency_days'] ) : 30, 'duration_ms' => isset( $_POST['duration_ms'] ) ? wp_unslash( $_POST['duration_ms'] ) : 0, 'reduced_duration_ms' => isset( $_POST['reduced_duration_ms'] ) ? wp_unslash( $_POST['reduced_duration_ms'] ) : 900,
			'brand_name' => isset( $_POST['brand_name'] ) ? wp_unslash( $_POST['brand_name'] ) : '', 'brand_claim' => isset( $_POST['brand_claim'] ) ? wp_unslash( $_POST['brand_claim'] ) : '', 'brand_language' => isset( $_POST['brand_language'] ) ? wp_unslash( $_POST['brand_language'] ) : 'en-US',
			'eligible_routes' => isset( $_POST['eligible_routes'] ) ? wp_unslash( $_POST['eligible_routes'] ) : '/', 'suppressed_prefixes' => isset( $_POST['suppressed_prefixes'] ) ? wp_unslash( $_POST['suppressed_prefixes'] ) : '', 'starts_at' => isset( $_POST['starts_at'] ) ? wp_unslash( $_POST['starts_at'] ) : '', 'ends_at' => isset( $_POST['ends_at'] ) ? wp_unslash( $_POST['ends_at'] ) : '',
			'analytics_enabled' => $this->bool_post( 'analytics_enabled' ), 'adaptive_mode' => $this->bool_post( 'adaptive_mode' ), 'never_show_enabled' => $this->bool_post( 'never_show_enabled' ), 'replay_enabled' => $this->bool_post( 'replay_enabled' ), 'version_replay_enabled' => $this->bool_post( 'version_replay_enabled' ), 'guest_reconcile_enabled' => $this->bool_post( 'guest_reconcile_enabled' ), 'instant_exit_enabled' => $this->bool_post( 'instant_exit_enabled' ), 'data_saver_static' => $this->bool_post( 'data_saver_static' ), 'performance_circuit_breaker' => $this->bool_post( 'performance_circuit_breaker' ), 'accessibility_profiles' => $this->bool_post( 'accessibility_profiles' ), 'pwa_precache_enabled' => $this->bool_post( 'pwa_precache_enabled' ), 'rollback_snapshots_enabled' => $this->bool_post( 'rollback_snapshots_enabled' ),
			'performance_budget_ms' => isset( $_POST['performance_budget_ms'] ) ? wp_unslash( $_POST['performance_budget_ms'] ) : 120, 'default_accessibility_profile' => isset( $_POST['default_accessibility_profile'] ) ? wp_unslash( $_POST['default_accessibility_profile'] ) : 'auto',
		);
		$expected = isset( $_POST['config_version'] ) ? absint( $_POST['config_version'] ) : 0; $result = SWI_Config::save( $raw, $expected ); if ( is_wp_error( $result ) ) $this->redirect_notice( 'error', $result->get_error_code() ); $this->redirect_notice( 'success', 'saved' );
	}
	public function reset_settings() { $this->require_manage(); check_admin_referer( 'swi_reset_settings' ); $current = SWI_Config::get(); $result = SWI_Config::save( SWI_Config::defaults(), (int) $current['config_version'] ); if ( is_wp_error( $result ) ) $this->redirect_notice( 'error', $result->get_error_code() ); $this->redirect_notice( 'success', 'reset' ); }
	public function approve_visual() { $this->require_manage(); if ( ! swi_current_user_can_approve() ) wp_die( esc_html__( 'Founder approval capability is required.', 'sabri-welcome-intro' ), '', array( 'response' => 403 ) ); check_admin_referer( 'swi_approve_visual' ); $expected = isset( $_POST['config_version'] ) ? absint( $_POST['config_version'] ) : 0; $result = SWI_Config::approve_visual( $expected ); if ( is_wp_error( $result ) ) $this->redirect_notice( 'error', $result->get_error_code() ); $this->redirect_notice( 'success', 'approved' ); }
	public function restore_snapshot() { $this->require_manage(); check_admin_referer( 'swi_restore_snapshot' ); $expected = isset( $_POST['config_version'] ) ? absint( $_POST['config_version'] ) : 0; $index = isset( $_POST['snapshot_index'] ) ? absint( $_POST['snapshot_index'] ) : 999; $result = SWI_Config::restore_snapshot( $index, $expected ); if ( is_wp_error( $result ) ) $this->redirect_notice( 'error', $result->get_error_code() ); $this->redirect_notice( 'success', 'restored' ); }
	private function redirect_notice( $type, $code ) { $url = add_query_arg( array( 'page' => 'sabri-welcome-intro', 'swi_notice' => sanitize_key( $type ), 'swi_code' => sanitize_key( $code ) ), admin_url( 'options-general.php' ) ); wp_safe_redirect( $url ); exit; }

	public function render_page() {
		if ( ! swi_current_user_can_manage() ) return; $config = SWI_Config::get(); $check = SWI_System_Check::snapshot(); $audit = array_slice( SWI_Config::audit_log(), 0, 20 ); $snapshots = SWI_Config::approved_snapshots(); $notice = isset( $_GET['swi_notice'] ) ? sanitize_key( wp_unslash( $_GET['swi_notice'] ) ) : ''; $code = isset( $_GET['swi_code'] ) ? sanitize_key( wp_unslash( $_GET['swi_code'] ) ) : '';
		?>
		<div class="wrap swi-admin-wrap"><h1><?php esc_html_e( 'Sabri Welcome Intro — Future Welcome Experience 1.1', 'sabri-welcome-intro' ); ?></h1>
		<p><?php esc_html_e( 'File 13 owns only the accessible, non-blocking welcome experience and its privacy-minimal preferences. File 20 remains shell owner and File 25 remains global visual-token owner.', 'sabri-welcome-intro' ); ?></p>
		<?php if ( $notice ) : ?><div class="notice <?php echo 'success' === $notice ? 'notice-success' : 'notice-error'; ?> is-dismissible"><p><?php echo esc_html( 'success' === $notice ? sprintf( __( 'Operation completed: %s', 'sabri-welcome-intro' ), $code ) : sprintf( __( 'Operation failed: %s', 'sabri-welcome-intro' ), $code ) ); ?></p></div><?php endif; ?>
		<div class="swi-admin-grid"><section class="swi-admin-card"><h2><?php esc_html_e( 'Governed configuration', 'sabri-welcome-intro' ); ?></h2>
		<form action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>" method="post"><input type="hidden" name="action" value="swi_save_settings"><input type="hidden" name="config_version" value="<?php echo esc_attr( $config['config_version'] ); ?>"><?php wp_nonce_field( 'swi_save_settings' ); ?>
		<table class="form-table" role="presentation">
		<tr><th><?php esc_html_e( 'Enabled', 'sabri-welcome-intro' ); ?></th><td><label><input type="checkbox" name="enabled" value="1" <?php checked( 1, $config['enabled'] ); ?>> <?php esc_html_e( 'Eligible routes only', 'sabri-welcome-intro' ); ?></label></td></tr>
		<tr><th><label for="swi-frequency"><?php esc_html_e( 'Frequency', 'sabri-welcome-intro' ); ?></label></th><td><input id="swi-frequency" type="number" min="30" max="365" name="frequency_days" value="<?php echo esc_attr( $config['frequency_days'] ); ?>"> <?php esc_html_e( 'days minimum', 'sabri-welcome-intro' ); ?></td></tr>
		<tr><th><label for="swi-duration"><?php esc_html_e( 'Automatic close', 'sabri-welcome-intro' ); ?></label></th><td><input id="swi-duration" type="number" min="0" max="30000" step="100" name="duration_ms" value="<?php echo esc_attr( $config['duration_ms'] ); ?>"> ms <p class="description"><?php esc_html_e( '0 means no forced close. Any nonzero timing requires an approved visual specification.', 'sabri-welcome-intro' ); ?></p></td></tr>
		<tr><th><label for="swi-reduced"><?php esc_html_e( 'Reduced-motion duration', 'sabri-welcome-intro' ); ?></label></th><td><input id="swi-reduced" type="number" min="250" max="1500" step="50" name="reduced_duration_ms" value="<?php echo esc_attr( $config['reduced_duration_ms'] ); ?>"> ms</td></tr>
		<tr><th><label for="swi-name"><?php esc_html_e( 'Brand name', 'sabri-welcome-intro' ); ?></label></th><td><input id="swi-name" class="regular-text" maxlength="120" name="brand_name" value="<?php echo esc_attr( $config['brand_name'] ); ?>"></td></tr>
		<tr><th><label for="swi-claim"><?php esc_html_e( 'Brand claim', 'sabri-welcome-intro' ); ?></label></th><td><textarea id="swi-claim" class="large-text" rows="3" maxlength="280" name="brand_claim"><?php echo esc_textarea( $config['brand_claim'] ); ?></textarea></td></tr>
		<tr><th><label for="swi-lang"><?php esc_html_e( 'Copy language', 'sabri-welcome-intro' ); ?></label></th><td><input id="swi-lang" class="regular-text" maxlength="35" name="brand_language" value="<?php echo esc_attr( $config['brand_language'] ); ?>"></td></tr>
		<tr><th><label for="swi-eligible"><?php esc_html_e( 'Eligible routes', 'sabri-welcome-intro' ); ?></label></th><td><textarea id="swi-eligible" class="large-text code" rows="4" name="eligible_routes"><?php echo esc_textarea( implode( "\n", (array) $config['eligible_routes'] ) ); ?></textarea></td></tr>
		<tr><th><label for="swi-suppressed"><?php esc_html_e( 'Suppressed route prefixes', 'sabri-welcome-intro' ); ?></label></th><td><textarea id="swi-suppressed" class="large-text code" rows="8" name="suppressed_prefixes"><?php echo esc_textarea( implode( "\n", (array) $config['suppressed_prefixes'] ) ); ?></textarea></td></tr>
		<tr><th><?php esc_html_e( 'Schedule', 'sabri-welcome-intro' ); ?></th><td><input type="datetime-local" name="starts_at" value="<?php echo esc_attr( $this->datetime_local( $config['starts_at'] ) ); ?>"> — <input type="datetime-local" name="ends_at" value="<?php echo esc_attr( $this->datetime_local( $config['ends_at'] ) ); ?>"></td></tr>
		<tr><th><label for="swi-budget"><?php esc_html_e( 'Performance circuit budget', 'sabri-welcome-intro' ); ?></label></th><td><input id="swi-budget" type="number" min="40" max="1000" name="performance_budget_ms" value="<?php echo esc_attr( $config['performance_budget_ms'] ); ?>"> ms</td></tr>
		<tr><th><label for="swi-profile"><?php esc_html_e( 'Default accessibility profile', 'sabri-welcome-intro' ); ?></label></th><td><select id="swi-profile" name="default_accessibility_profile"><?php foreach ( SWI_Experience::ACCESSIBILITY_PROFILES as $profile ) : ?><option value="<?php echo esc_attr( $profile ); ?>" <?php selected( $profile, $config['default_accessibility_profile'] ); ?>><?php echo esc_html( $profile ); ?></option><?php endforeach; ?></select></td></tr>
		</table><h3><?php esc_html_e( 'Future safeguards and capabilities', 'sabri-welcome-intro' ); ?></h3>
		<?php $flags = array( 'adaptive_mode' => 'Adaptive intro', 'never_show_enabled' => 'Never Show Again', 'replay_enabled' => 'Signed replay', 'version_replay_enabled' => 'Version-aware replay', 'guest_reconcile_enabled' => 'Guest → account reconciliation', 'instant_exit_enabled' => 'Instant interaction exit', 'data_saver_static' => 'Data Saver static mode', 'performance_circuit_breaker' => 'Performance circuit breaker', 'accessibility_profiles' => 'Accessibility profiles', 'pwa_precache_enabled' => 'PWA/offline precache adapter', 'rollback_snapshots_enabled' => 'Rollback snapshots', 'analytics_enabled' => 'Privacy-safe aggregate analytics' ); foreach ( $flags as $key => $label ) : ?><label style="display:block;margin:.35rem 0"><input type="checkbox" name="<?php echo esc_attr( $key ); ?>" value="1" <?php checked( 1, $config[ $key ] ); ?>> <?php echo esc_html( $label ); ?></label><?php endforeach; ?>
		<?php submit_button(); ?></form><form action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>" method="post" data-swi-confirm-reset><input type="hidden" name="action" value="swi_reset_settings"><?php wp_nonce_field( 'swi_reset_settings' ); ?><?php submit_button( __( 'Restore Safe Defaults', 'sabri-welcome-intro' ), 'secondary', 'submit', false ); ?></form></section>

		<section class="swi-admin-card"><h2><?php esc_html_e( 'Advanced Preview Lab', 'sabri-welcome-intro' ); ?></h2><p><?php esc_html_e( 'Signed previews are noindex/no-cache and never mutate public recurrence state.', 'sabri-welcome-intro' ); ?></p>
		<?php $states = array( 'default','reduced','skipped','disabled','error','data-saver','offline' ); foreach ( $states as $state ) : foreach ( array( 'full','light','static' ) as $variant ) : $url = wp_nonce_url( add_query_arg( array( 'swi_state' => $state, 'swi_variant' => $variant, 'swi_profile' => 'auto' ), home_url( '/welcome-intro-preview/' ) ), 'swi_preview' ); ?><a class="button" style="margin:.15rem" href="<?php echo esc_url( $url ); ?>" target="_blank" rel="noopener noreferrer"><?php echo esc_html( $state . ' / ' . $variant ); ?></a><?php endforeach; endforeach; ?>
		<h3><?php esc_html_e( 'Accessibility previews', 'sabri-welcome-intro' ); ?></h3><?php foreach ( SWI_Experience::ACCESSIBILITY_PROFILES as $profile ) : $url = wp_nonce_url( add_query_arg( array( 'swi_state' => 'default', 'swi_variant' => 'static', 'swi_profile' => $profile ), home_url( '/welcome-intro-preview/' ) ), 'swi_preview' ); ?><a class="button" style="margin:.15rem" href="<?php echo esc_url( $url ); ?>" target="_blank" rel="noopener noreferrer"><?php echo esc_html( $profile ); ?></a><?php endforeach; ?>
		<h2><?php esc_html_e( 'Founder visual approval', 'sabri-welcome-intro' ); ?></h2><p><strong><?php echo esc_html( (string) $config['approval_state'] ); ?></strong> — <?php echo esc_html( $check['approval_current'] ? __( 'current baseline matches approval', 'sabri-welcome-intro' ) : __( 'approval absent or baseline changed', 'sabri-welcome-intro' ) ); ?></p><code><?php echo esc_html( (string) $check['current_visual_baseline_hash'] ); ?></code>
		<?php if ( swi_current_user_can_approve() ) : ?><form action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>" method="post"><input type="hidden" name="action" value="swi_approve_visual"><input type="hidden" name="config_version" value="<?php echo esc_attr( $config['config_version'] ); ?>"><?php wp_nonce_field( 'swi_approve_visual' ); ?><?php submit_button( __( 'Approve Current Visual Baseline', 'sabri-welcome-intro' ), 'primary', 'submit', false ); ?></form><?php endif; ?>
		<h2><?php esc_html_e( 'Rollback snapshots', 'sabri-welcome-intro' ); ?></h2><?php if ( empty( $snapshots ) ) : ?><p><?php esc_html_e( 'No snapshots recorded yet.', 'sabri-welcome-intro' ); ?></p><?php else : ?><table class="widefat striped"><thead><tr><th>#</th><th><?php esc_html_e( 'Reason', 'sabri-welcome-intro' ); ?></th><th><?php esc_html_e( 'Created', 'sabri-welcome-intro' ); ?></th><th><?php esc_html_e( 'Action', 'sabri-welcome-intro' ); ?></th></tr></thead><tbody><?php foreach ( $snapshots as $index => $snapshot ) : ?><tr><td><?php echo esc_html( $index ); ?></td><td><?php echo esc_html( $snapshot['reason'] ?? '' ); ?></td><td><?php echo esc_html( $snapshot['created_at'] ?? '' ); ?></td><td><form action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>" method="post"><input type="hidden" name="action" value="swi_restore_snapshot"><input type="hidden" name="snapshot_index" value="<?php echo esc_attr( $index ); ?>"><input type="hidden" name="config_version" value="<?php echo esc_attr( $config['config_version'] ); ?>"><?php wp_nonce_field( 'swi_restore_snapshot' ); ?><button class="button" type="submit"><?php esc_html_e( 'Restore', 'sabri-welcome-intro' ); ?></button></form></td></tr><?php endforeach; ?></tbody></table><?php endif; ?></section>

		<section class="swi-admin-card"><h2><?php esc_html_e( 'Repository/runtime health snapshot', 'sabri-welcome-intro' ); ?></h2><table class="widefat striped"><tbody><?php foreach ( $check as $key => $value ) : ?><tr><th><?php echo esc_html( $key ); ?></th><td><code><?php echo esc_html( is_array( $value ) ? wp_json_encode( $value ) : ( is_bool( $value ) ? ( $value ? 'true' : 'false' ) : (string) $value ) ); ?></code></td></tr><?php endforeach; ?></tbody></table><p><em><?php esc_html_e( 'This health panel is repository/runtime evidence only; it does not prove staging or live deployment.', 'sabri-welcome-intro' ); ?></em></p>
		<h2><?php esc_html_e( 'Recent audit', 'sabri-welcome-intro' ); ?></h2><table class="widefat striped"><tbody><?php foreach ( $audit as $entry ) : ?><tr><td><?php echo esc_html( $entry['occurred_at'] ?? '' ); ?></td><td><?php echo esc_html( $entry['event'] ?? '' ); ?></td><td><?php echo esc_html( implode( ', ', (array) ( $entry['changed_keys'] ?? array() ) ) ); ?></td></tr><?php endforeach; ?></tbody></table></section>
		</div></div><?php
	}
	private function datetime_local( $value ) { if ( ! $value ) return ''; try { $date = new DateTimeImmutable( (string) $value ); if ( function_exists( 'wp_timezone' ) ) $date = $date->setTimezone( wp_timezone() ); return $date->format( 'Y-m-d\TH:i' ); } catch ( Exception $exception ) { return ''; } }
}
