#!/usr/bin/env python3
from pathlib import Path
import json, re, sys
root=Path(__file__).resolve().parents[1]
def txt(rel): return (root/rel).read_text(encoding='utf-8')
def exists(rel): return (root/rel).exists()
plugin=txt('sabri-welcome-intro/sabri-welcome-intro.php')
config=txt('sabri-welcome-intro/includes/class-swi-config.php')
elig=txt('sabri-welcome-intro/includes/class-swi-eligibility.php')
render=txt('sabri-welcome-intro/includes/class-swi-renderer.php')
js=txt('sabri-welcome-intro/assets/js/welcome-intro.js')
css=txt('sabri-welcome-intro/assets/css/welcome-intro.css')
rest=txt('sabri-welcome-intro/includes/class-swi-rest.php')
privacy=txt('sabri-welcome-intro/includes/class-swi-privacy.php')
contracts=txt('sabri-welcome-intro/includes/class-swi-contracts.php')
system=txt('sabri-welcome-intro/includes/class-swi-system-check.php')
functions=txt('sabri-welcome-intro/includes/functions.php')
admin=txt('sabri-welcome-intro/includes/class-swi-admin.php')
builder=txt('tools/build-release.py')
checks=[]
def add(name, cond): checks.append((name, bool(cond)))
add('exact software version 1.1.0', 'Version: 1.1.0' in plugin and "SWI_VERSION', '1.1.0" in plugin)
add('schema version aligned 1.1.0', "SWI_SCHEMA_VERSION', '1.1.0" in plugin)
add('governing recurrence minimum 30 days', "'frequency_days'                => 30" in config and 'max( 30' in config)
add('same-session suppression key', 'SESSION_KEY' in config and 'sessionKey' in js)
add('multi-tab claim suppression', 'anotherTabClaimed' in js and 'claimKey' in js)
add('no forced historical eight-second close', "'duration_ms'                   => 0" in config and 'duration > 0' in js)
add('exact Sabri Green fallback', '#087a4e' in css.lower())
add('orange remains contextual accent', '--swi-accent' in css and 'linear-gradient' in css)
add('approved default brand claim', 'The Tridimensional Healing System of Soul, Vital Force, and Matter' in config)
add('File 20 shell registry integration', 'sabri_shell_module_registry' in contracts and 'sabri_shell_welcome_intro' in contracts)
add('no duplicate navigation ownership', 'wp_nav_menu' not in render and 'navigation' not in contracts.lower())
add('suppressed login route', "'/login'" in config)
add('suppressed recovery/account route', "'/account'" in config and "'/support'" in config)
add('suppressed clinical route', "'/clinical'" in config)
add('suppressed emergency route', "'/emergency'" in config)
add('safe mode cannot be bypassed by replay', elig.find('safe_mode_active') < elig.find('authorized_replay'))
add('nonvisual requests suppressed', 'non_visual_request' in elig and 'non_page_request' in elig)
add('route allowlist enforced', 'route_not_eligible' in elig)
add('runtime eligibility filter monotonic', 'empty( $decision[\'eligible\'] ) && ! empty( $filtered[\'eligible\'] )' in elig)
add('runtime configuration restriction layer', 'restrict_runtime_config' in config)
add('runtime cannot shorten recurrence', "max( absint( $local['frequency_days']" in config)
add('runtime suppression set is additive', "array_merge( (array) $local['suppressed_prefixes']" in config)
add('runtime analytics cannot opt in', "! empty( $local['analytics_enabled'] ) && ! empty( $runtime['analytics_enabled'] )" in config)
add('schedule can only narrow', "strtotime( $runtime_start ) > strtotime( $local_start )" in config and "strtotime( $runtime_end ) < strtotime( $local_end )" in config)
add('atomic config write lock', 'OPTION_WRITE_LOCK' in config and 'add_option( self::OPTION_WRITE_LOCK' in config)
add('optimistic version conflict', 'swi_config_conflict' in config)
add('write lock released in finally', 'finally { self::release_write_lock' in config)
add('bounded audit trail', 'array_slice( $log, -100 )' in config)
add('adaptive full/light/static variants', 'chooseVariant' in js and 'swi-variant-light' in css and 'swi-variant-static' in css)
add('Never Show Again device state', 'neverIntro' in js and 'data-swi-never' in render)
add('Never Show Again account state', 'USER_META_NEVER' in config and 'account_never_show' in elig)
add('signed replay nonce', 'swi_public_replay' in render and '_swi_nonce' in render)
add('replay nonce same-origin protection', 'wp_validate_redirect' in functions and 'home_host' in functions)
add('version-aware replay', 'version_replay_enabled' in config and 'versionAllowsReplay' in js)
add('cross-device preference endpoint', "'/preference'" in rest and 'USER_META_PROFILE' in rest)
add('guest to account reconciliation', 'reconcileGuestToAccount' in js)
add('instant interaction exit', 'onPointerIntent' in js and 'onWheelIntent' in js)
add('Data Saver static mode', 'saveData' in js and 'data_saver_static' in config)
add('low-bandwidth adaptive mode', "effectiveType === '2g'" in js)
add('performance circuit breaker', 'maybeTripPerformanceCircuit' in js and 'performance_budget_ms' in config)
add('reduced motion static variant', 'prefers-reduced-motion' in css and "variant === 'static'" in js)
add('accessibility profiles', 'ACCESSIBILITY_PROFILES' in txt('sabri-welcome-intro/includes/class-swi-experience.php') and '.swi-a11y-high-contrast' in css)
add('focus trap and Escape', "event.key === 'Escape'" in js and "event.key !== 'Tab'" in js)
add('focus restoration', 'restoreFocus' in js and 'previousFocus' in js)
add('screen-reader dialog semantics', 'role="dialog"' in render and 'aria-modal="true"' in render and 'aria-describedby' in render)
add('no autoplay sound', '<audio' not in render.lower() and 'Audio(' not in js)
add('no remote runtime dependency', 'http://' not in js and 'https://' not in js)
add('localized copy resolver', 'localized_copy' in config and 'localized_copy' in txt('sabri-welcome-intro/includes/class-swi-experience.php'))
add('RTL logical styling', 'inset-inline' in css and '[dir="rtl"]' in css)
add('safe-area styling', 'safe-area-inset' in css)
add('mobile responsive layout', '@media (max-width: 540px)' in css)
add('zoom overflow resilience', 'overflow-wrap: anywhere' in css and 'overflow: auto' in css)
add('advanced preview states', "'data-saver','offline'" in render and "'disabled','error'" in render)
add('advanced preview variants', 'data-preview-variant' in render and 'swi_variant' in render)
add('preview accessibility profiles', 'swi_profile' in render and 'Accessibility previews' in admin)
add('Founder visual approval action', 'approve_visual' in config and 'admin_post_swi_approve_visual' in admin)
add('visual baseline hashing', 'visual_baseline_hash' in txt('sabri-welcome-intro/includes/class-swi-experience.php') and 'approval_current' in system)
add('rollback snapshots bounded', 'array_slice( $snapshots, -5 )' in config and 'restore_snapshot' in config)
add('privacy export Future profile', 'Accessibility profile' in privacy and 'USER_META_PROFILE' in privacy)
add('privacy erasure Future profile', 'USER_META_EXPERIENCE, SWI_Config::USER_META_PROFILE' in privacy)
add('privacy reset preserves accessibility choice', 'swi_reset_intro' in privacy and 'USER_META_PROFILE ) as $key' not in privacy.split('swi_reset_intro')[-1])
add('aggregate telemetry allowlist', 'ALLOWED_EVENTS' in txt('sabri-welcome-intro/includes/class-swi-analytics.php'))
add('analytics no IP/user-agent collection', 'REMOTE_ADDR' not in txt('sabri-welcome-intro/includes/class-swi-analytics.php') and 'HTTP_USER_AGENT' not in txt('sabri-welcome-intro/includes/class-swi-analytics.php'))
add('separate public event nonce', 'X-SWI-Nonce' in rest)
add('REST idempotency keys', 'idempotency_key' in rest and 'duplicate' in rest)
add('REST bounded rate limits', 'rate_limited' in rest and 'MINUTE_IN_SECONDS' in rest)
add('health dashboard truth boundary', 'production_truth' in system and 'staging/live/operational' in system)
add('PWA precache is adapter only', 'sabri_pwa_precache_assets' in contracts and 'serviceWorker.register' not in js)
add('PWA assets local only', all(x in txt('sabri-welcome-intro/includes/class-swi-experience.php') for x in ['assets/css/welcome-intro.css','assets/js/welcome-intro.js','assets/images/sabri-sh-logo.svg']))
add('activation snapshot method exists', 'ensure_approved_snapshot' in config and 'ensure_approved_snapshot' in txt('sabri-welcome-intro/includes/class-swi-activator.php'))
add('non-destructive uninstall default', 'SWI_PURGE_ON_UNINSTALL' in txt('sabri-welcome-intro/uninstall.php'))
add('Future PHP regression suite present', exists('tests/future-superset-regressions.php'))
add('Future runtime suite present', exists('tests/future-superset-runtime.test.js'))
add('deterministic package builder version 1.1.0', "version = '1.1.0'" in builder and 'ZIP_STORED' in builder)
add('reproducible package test version 1.1.0', '1.1.0.zip' in txt('tests/reproducible-package.test.py'))
add('no obsolete payload fragments', not list((root/'.github').glob('file13-*.part*')))
add('permanent CI is not a hold stub', exists('.github/workflows/corrective-integrity.yml') and 'atomic Future Superset update in progress' not in txt('.github/workflows/corrective-integrity.yml'))
add('File 13 contract declares exactly 18 enhancements', txt('sabri-welcome-intro/includes/functions.php').count("'adaptive_intro'") == 1 and len(re.findall(r"'(?:adaptive_intro|never_show|signed_replay|version_awareness|cross_device_sync|guest_account_reconcile|instant_exit|data_saver|performance_circuit_breaker|accessibility_profiles|localized_copy|preview_lab|founder_approval|visual_baseline|privacy_safe_telemetry|health_dashboard|rollback_snapshots|pwa_offline_compatibility)'", functions)) == 18)
add('repository documentation identifies software 1.1.0', '1.1.0' in txt('README.md'))
add('status document preserves external gates', 'staging' in txt('STATUS.md').lower() and 'live' in txt('STATUS.md').lower() and 'operational' in txt('STATUS.md').lower())
if len(checks) != 80:
    print(f'INTERNAL ERROR: expected 80 rounds, got {len(checks)}'); sys.exit(2)
for idx,(name,ok) in enumerate(checks,1):
    print(f'ROUND {idx:02d}: {"PASS" if ok else "FAIL"} — {name}')
    if not ok:
        print(f'EIGHTY-ROUND REVIEW STOPPED AT ROUND {idx:02d}; fix before proceeding.')
        sys.exit(1)
print('EIGHTY-ROUND REVIEW: 80/80 PASS — zero known unresolved defects in this deterministic repository scope')
