'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const test = require('node:test');
const vm = require('node:vm');
const source = fs.readFileSync(path.join(__dirname, '..', 'sabri-welcome-intro', 'assets', 'js', 'welcome-intro.js'), 'utf8');

function classList() { const set = new Set(); return { add(...x){x.forEach(v=>set.add(v));}, remove(...x){x.forEach(v=>set.delete(v));}, contains(x){return set.has(x);}, set }; }
function storage(initial={}) { const map = new Map(Object.entries(initial)); return { getItem(k){return map.has(k)?map.get(k):null;}, setItem(k,v){map.set(k,String(v));}, removeItem(k){map.delete(k);}, map }; }
function element(tag, document) { const attrs=new Map(); const listeners=new Map(); return { tagName:tag,nodeType:1,parentElement:null,children:[],isConnected:true,classList:classList(),listeners,setAttribute(k,v){attrs.set(k,String(v));},getAttribute(k){return attrs.has(k)?attrs.get(k):null;},hasAttribute(k){return attrs.has(k);},removeAttribute(k){attrs.delete(k);},addEventListener(k,fn){listeners.set(k,fn);},removeEventListener(k,fn){if(listeners.get(k)===fn)listeners.delete(k);},focus(){document.activeElement=this;},remove(){this.isConnected=false;if(this.parentElement)this.parentElement.children=this.parentElement.children.filter(c=>c!==this);},querySelector(){return null;} }; }
function runtime(options={}) {
  const events=[]; const fetches=[]; const timers=new Map(); let nextTimer=1; let cookie=''; let perf=options.performanceStart||0;
  const document={activeElement:null,hidden:false,_listeners:new Map(),addEventListener(k,fn){this._listeners.set(k,fn);},removeEventListener(k,fn){if(this._listeners.get(k)===fn)this._listeners.delete(k);},dispatchEvent(e){events.push(e);return true;}};
  const html=element('HTML',document), body=element('BODY',document), previous=element('A',document), intro=element('ASIDE',document), close=element('BUTTON',document), cont=element('BUTTON',document), skip=element('BUTTON',document), never=element('BUTTON',document), ambient=element('DIV',document);
  html.children=[body];body.parentElement=html;document.documentElement=html;document.body=body;previous.parentElement=body;intro.parentElement=body;body.children=[previous,intro];document.activeElement=previous;[close,cont,skip,never,ambient].forEach(x=>x.parentElement=intro);intro.children=[ambient,close,cont,skip,never];
  const attrs={hidden:'','data-preview':options.preview?'1':'0','data-preview-state':options.previewState||'default','data-preview-variant':options.previewVariant||'full','data-replay':options.replay?'1':'0','data-frequency-days':'30','data-duration':String(options.duration===undefined?0:options.duration),'data-reduced-duration':'900','data-config-version':'7','data-experience-version':'1.1.0','data-cookie-name':'swi_seen_at_v1','data-session-key':'swi_seen_session_v1','data-local-key':'swi_seen_at_v1','data-claim-key':'swi_claim_v1','data-never-key':'swi_never_show_v1','data-profile-key':'swi_a11y_profile_v1','data-rest-url':options.restUrl||'','data-rest-nonce':options.restNonce||'','data-event-nonce':options.eventNonce||'','data-analytics':options.analytics?'1':'0','data-account-authoritative':options.account?'1':'0','data-user-id':options.account?'5':'0','data-account-seen-at':String(options.accountSeenAt||0),'data-account-never-show':options.accountNever?'1':'0','data-account-experience':options.accountExperience||'','data-accessibility-profile':options.profile||'auto','data-adaptive':'1','data-never-show-enabled':'1','data-replay-enabled':'1','data-version-replay':'1','data-guest-reconcile':'1','data-instant-exit':'1','data-data-saver-static':'1','data-performance-circuit':'1','data-performance-budget':String(options.performanceBudget||120)}; Object.entries(attrs).forEach(([k,v])=>intro.setAttribute(k,v));
  intro.querySelector=q=>q==='[data-swi-close]'?close:q==='[data-swi-continue]'?cont:q==='[data-swi-skip]'?skip:q==='[data-swi-never]'?never:q==='.swi-ambient'?ambient:null; document.getElementById=id=>id==='swi-intro'?intro:null; Object.defineProperty(document,'cookie',{get(){return cookie;},set(v){cookie=v;}});
  const localStorage=storage(options.local||{}), sessionStorage=storage(options.session||{}), navigator={connection:options.connection||null,deviceMemory:options.deviceMemory,hardwareConcurrency:options.hardwareConcurrency,onLine:options.offline?false:true};
  const window={location:{protocol:'https:'},localStorage,sessionStorage,navigator,performance:{now(){perf += options.performanceStep||0; return perf;}},matchMedia(){return {matches:Boolean(options.reduced)};},getComputedStyle(){return {getPropertyValue(){return '1';}};},requestAnimationFrame(fn){fn();},setTimeout(fn,delay){const id=nextTimer++;timers.set(id,{fn,delay});return id;},clearTimeout(id){timers.delete(id);},fetch(url,init){fetches.push({url,init});return Promise.resolve({ok:true});},crypto:{getRandomValues(a){for(let i=0;i<a.length;i++)a[i]=i+1;return a;}}};
  function CustomEvent(name,init){this.type=name;this.detail=init.detail;}
  vm.runInNewContext(source,{Array,Boolean,CustomEvent,Date,JSON,Math,Number,Promise,String,Uint32Array,decodeURIComponent,document,encodeURIComponent,navigator,parseInt,window},{filename:'welcome-intro.js'});
  return {intro,body,previous,close,cont,skip,never,events,fetches,timers,localStorage,sessionStorage,cookie:()=>cookie};
}

test('default Future Welcome has no forced close timer',()=>{const r=runtime();assert.equal(r.intro.isConnected,true);assert.equal([...r.timers.values()].some(t=>t.delay>=1200),false);});
test('Never Show Again persists device preference and closes',()=>{const r=runtime();r.never.listeners.get('click')();assert.equal(r.localStorage.map.get('swi_never_show_v1'),'1');const t=[...r.timers.values()].find(x=>x.delay===220);assert.ok(t);t.fn();assert.equal(r.intro.isConnected,false);});
test('device Never Show Again suppresses ordinary future render',()=>{const r=runtime({local:{swi_never_show_v1:'1'}});assert.equal(r.intro.isConnected,false);});
test('signed replay bypasses local recurrence and Never Show Again',()=>{const r=runtime({replay:true,local:{swi_never_show_v1:'1',swi_seen_at_v1:JSON.stringify({ts:Date.now(),version:'1.1.0'})}});assert.equal(r.intro.isConnected,true);assert.ok(r.events.some(e=>e.type==='swi:replay'));});
test('new experience version replays an older version-aware local record',()=>{const r=runtime({local:{swi_seen_at_v1:JSON.stringify({ts:Date.now(),version:'1.0.0'})}});assert.equal(r.intro.isConnected,true);});
test('same experience recent record remains suppressed',()=>{const r=runtime({local:{swi_seen_at_v1:JSON.stringify({ts:Date.now(),version:'1.1.0'})}});assert.equal(r.intro.isConnected,false);});
test('Save-Data selects static variant',()=>{const r=runtime({connection:{saveData:true,effectiveType:'4g'}});assert.equal(r.intro.classList.contains('swi-variant-static'),true);});
test('slow 2g selects light variant when Save-Data is off',()=>{const r=runtime({connection:{saveData:false,effectiveType:'2g'}});assert.equal(r.intro.classList.contains('swi-variant-light'),true);});
test('reduced motion selects static variant',()=>{const r=runtime({reduced:true});assert.equal(r.intro.classList.contains('swi-variant-static'),true);});
test('large-text accessibility profile is applied',()=>{const r=runtime({profile:'large-text'});assert.equal(r.intro.classList.contains('swi-a11y-large-text'),true);});
test('performance circuit breaker degrades to static if startup budget is exceeded',()=>{const r=runtime({performanceStep:200,performanceBudget:120});assert.equal(r.intro.classList.contains('swi-variant-static'),true);});
test('authenticated guest preference reconciliation posts only to same-origin REST preference endpoint',()=>{const recent=Date.now();const r=runtime({account:true,restUrl:'/wp-json/sabri-welcome-intro/v1',restNonce:'rest',accountSeenAt:0,local:{swi_seen_at_v1:JSON.stringify({ts:recent,version:'1.1.0'}),swi_never_show_v1:'1'}});const req=r.fetches.find(x=>x.url.endsWith('/preference'));assert.ok(req);assert.equal(req.init.headers['X-WP-Nonce'],'rest');const body=JSON.parse(req.init.body);assert.equal(body.never_show,1);assert.ok(body.idempotency_key);});
test('analytics event uses separate event nonce and aggregate variant name',()=>{const r=runtime({analytics:true,restUrl:'/wp-json/sabri-welcome-intro/v1',eventNonce:'event'});const req=r.fetches.find(x=>x.url.endsWith('/event'));assert.ok(req);assert.equal(req.init.headers['X-SWI-Nonce'],'event');});
test('preview data-saver state is visible static and does not mutate device persistence',()=>{const r=runtime({preview:true,previewState:'data-saver'});assert.equal(r.intro.classList.contains('swi-variant-static'),true);r.cont.listeners.get('click')();assert.equal(r.localStorage.map.has('swi_seen_at_v1'),false);});
