#!/usr/bin/env bash
set -euo pipefail
root="$(cd "$(dirname "$0")/.." && pwd)"
plugin="$root/sabri-welcome-intro"
pass=0
check() { if eval "$2"; then printf 'PASS: %s\n' "$1"; pass=$((pass+1)); else printf 'FAIL: %s\n' "$1"; exit 1; fi; }
check 'plugin declares version 1.1.0' "grep -q \"Version: 1.1.0\" '$plugin/sabri-welcome-intro.php' && grep -q \"SWI_VERSION', '1.1.0\" '$plugin/sabri-welcome-intro.php'"
check '30-day minimum exists in server contract' "grep -q \"max( 30\" '$plugin/includes/class-swi-config.php'"
check 'historical forced eight-second timeout is not the default' "grep -q \"'duration_ms'[[:space:]]*=>[[:space:]]*0\" '$plugin/includes/class-swi-config.php' && ! grep -q \"min( 8000\" '$plugin/includes/class-swi-config.php'"
check 'governing healing identity claim is the default' "grep -q \"The Tridimensional Healing System of Soul, Vital Force, and Matter\" '$plugin/includes/class-swi-config.php'"
check 'guest timestamp cookie uses SameSite Lax' "grep -q \"SameSite=Lax\" '$plugin/assets/js/welcome-intro.js'"
check 'overlay is hidden in markup and CSS by default' "grep -q 'tabindex=\"-1\" hidden' '$plugin/includes/class-swi-renderer.php' && grep -q '\\.swi-intro\\[hidden\\]' '$plugin/assets/css/welcome-intro.css'"
check 'primary identity uses exact Sabri Green with contextual orange' "grep -qi '#087a4e' '$plugin/assets/css/welcome-intro.css' && grep -qi '#087a4e' '$plugin/assets/images/sabri-sh-logo.svg' && grep -qi '#ff8a1f' '$plugin/assets/css/welcome-intro.css' && ! grep -Rqi '#087a3e' '$plugin'"
check 'SVG is path based and has no text element' "grep -q '<path' '$plugin/assets/images/sabri-sh-logo.svg' && ! grep -q '<text' '$plugin/assets/images/sabri-sh-logo.svg'"
check 'no autoplay sound or audio element exists' "! grep -RniE '<audio|Audio\\(|autoplay.*sound' '$plugin' --include='*.php' --include='*.js'"
check 'no remote runtime scripts or styles exist' "! grep -RniE 'wp_enqueue_(script|style).*https?://' '$plugin' --include='*.php'"
check 'admin writes require capability and nonce' "grep -q \"swi_current_user_can_manage()\" '$plugin/includes/class-swi-admin.php' && grep -q \"check_admin_referer\" '$plugin/includes/class-swi-admin.php'"
check 'Founder visual approval is separately capability gated' "grep -q \"swi_current_user_can_approve()\" '$plugin/includes/class-swi-admin.php' && grep -q \"swi_approve_visual\" '$plugin/includes/class-swi-admin.php'"
check 'preview and replay are signed and preview is noindex' "grep -q \"wp_verify_nonce\" '$plugin/includes/class-swi-renderer.php' && grep -q \"swi_public_replay\" '$plugin/includes/class-swi-renderer.php' && grep -q \"noindex\" '$plugin/includes/class-swi-renderer.php'"
check 'kill-switch contracts exist' "grep -q \"SABRI_PLATFORM_SAFE_MODE\" '$plugin/includes/class-swi-eligibility.php' && grep -q \"swi_force_disabled\" '$plugin/includes/class-swi-eligibility.php'"
check 'runtime configuration integration is restriction-only' "grep -q \"restrict_runtime_config\" '$plugin/includes/class-swi-config.php' && grep -q \"array_intersect\" '$plugin/includes/class-swi-config.php' && grep -q \"array_merge( (array) \\$local\['suppressed_prefixes'\]\" '$plugin/includes/class-swi-config.php'"
check 'eligibility integration cannot lift a local denial' "grep -q \"empty( \\$decision\['eligible'\] ) && ! empty( \\$filtered\['eligible'\] )\" '$plugin/includes/class-swi-eligibility.php'"
check 'File 20 registry and slot contracts exist' "grep -q \"sabri_shell_module_registry\" '$plugin/includes/class-swi-contracts.php' && grep -q \"sabri_shell_welcome_intro\" '$plugin/includes/class-swi-contracts.php'"
check 'File 25 token fallbacks are consumed' "grep -q -- \"--sabri-color-primary\" '$plugin/assets/css/welcome-intro.css'"
check 'privacy export and erasure include Future preferences' "grep -q \"wp_privacy_personal_data_exporters\" '$plugin/includes/class-swi-privacy.php' && grep -q \"wp_privacy_personal_data_erasers\" '$plugin/includes/class-swi-privacy.php' && grep -q \"USER_META_PROFILE\" '$plugin/includes/class-swi-privacy.php'"
check 'cross-device preference mutation is authenticated and idempotent' "grep -q \"'/preference'\" '$plugin/includes/class-swi-rest.php' && grep -q \"permission_callback.*is_user_logged_in\" '$plugin/includes/class-swi-rest.php' && grep -q \"swi_pref_\" '$plugin/includes/class-swi-rest.php'"
check 'aggregate telemetry has no IP or user-agent fingerprint fields' "! grep -qE 'REMOTE_ADDR|HTTP_USER_AGENT' '$plugin/includes/class-swi-analytics.php' && grep -q \"ALLOWED_EVENTS\" '$plugin/includes/class-swi-analytics.php'"
check 'uninstall is non-destructive by default' "grep -q \"SWI_PURGE_ON_UNINSTALL\" '$plugin/uninstall.php'"
check 'no private or secret material is present' "! grep -RniE '(BEGIN (RSA|OPENSSH|EC) PRIVATE KEY|api[_-]?key[[:space:]]*=[[:space:]]*[A-Za-z0-9]{16,}|password[[:space:]]*=[[:space:]]*[^[:space:]]+)' '$root' --exclude-dir=release"
printf 'STATIC CONTRACTS: %d passed, 0 failed\n' "$pass"
